[
    {
        "id": 4275902121,
        "domain": "test",
        "status": "failed",
        "reference": "ldscjq5m9r",
        "amount": 198,
        "message": null,
        "gateway_response": "Declined",
        "paid_at": null,
        "created_at": "2024-10-15T10:00:05.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": {
            "start_time": 1728986406,
            "time_spent": 7,
            "attempts": 1,
            "errors": 1,
            "success": false,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 6
                },
                {
                    "type": "error",
                    "message": "Error: Declined",
                    "time": 7
                }
            ]
        },
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_h8a4dp6fj2",
            "bin": "408408",
            "last4": "5408",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_tx5zByUbRL3ulmD3HbI0",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T10:00:05.000Z",
        "requested_amount": 198,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275874525,
        "domain": "test",
        "status": "success",
        "reference": "tlln9jetmp",
        "amount": 200,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T09:50:43.000Z",
        "created_at": "2024-10-15T09:50:34.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": {
            "start_time": 1728985837,
            "time_spent": 7,
            "attempts": 1,
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 2
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 5
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 7
                }
            ]
        },
        "fees": 6,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_7wkupe7w23",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T09:50:43.000Z",
        "createdAt": "2024-10-15T09:50:34.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275782642,
        "domain": "test",
        "status": "success",
        "reference": "vgkqku3ufk",
        "amount": 200,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T09:16:12.000Z",
        "created_at": "2024-10-15T09:15:57.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": {
            "start_time": 1728983759,
            "time_spent": 13,
            "attempts": 1,
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: mpesa",
                    "time": 2
                },
                {
                    "type": "action",
                    "message": "Set payment method to: null",
                    "time": 7
                },
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 8
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 11
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 13
                }
            ]
        },
        "fees": 6,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_17ttunrj8k",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T09:16:12.000Z",
        "createdAt": "2024-10-15T09:15:57.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275762972,
        "domain": "test",
        "status": "abandoned",
        "reference": "e13ewirq2b",
        "amount": 5000,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T09:08:05.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T09:08:05.000Z",
        "requested_amount": 5000,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275762936,
        "domain": "test",
        "status": "abandoned",
        "reference": "sxj3913mkm",
        "amount": 5000,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T09:08:04.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T09:08:04.000Z",
        "requested_amount": 5000,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275760754,
        "domain": "test",
        "status": "success",
        "reference": "mhpxoa7grd",
        "amount": 4000,
        "message": "test-3ds",
        "gateway_response": "[Test] Approved",
        "paid_at": "2024-10-15T09:07:47.000Z",
        "created_at": "2024-10-15T09:07:14.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": {
            "start_time": 1728983235,
            "time_spent": 33,
            "attempts": 1,
            "authentication": "3DS",
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: mpesa",
                    "time": 15
                },
                {
                    "type": "action",
                    "message": "Set payment method to: null",
                    "time": 20
                },
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 22
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 25
                },
                {
                    "type": "auth",
                    "message": "Authentication Required: 3DS",
                    "time": 26
                },
                {
                    "type": "action",
                    "message": "Third-party authentication window opened",
                    "time": 31
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 33
                },
                {
                    "type": "action",
                    "message": "Third-party authentication window closed",
                    "time": 33
                }
            ]
        },
        "fees": 116,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_36jtk670cs",
            "bin": "408408",
            "last4": "0409",
            "exp_month": "01",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_Qj0Ry1lYPHnMQUI4rJaW",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T09:07:47.000Z",
        "createdAt": "2024-10-15T09:07:14.000Z",
        "requested_amount": 4000,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275760035,
        "domain": "test",
        "status": "abandoned",
        "reference": "73hugul9c6",
        "amount": 200,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T09:06:56.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T09:06:56.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275701070,
        "domain": "test",
        "status": "success",
        "reference": "3nqinu3eyf",
        "amount": 200,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T08:48:46.000Z",
        "created_at": "2024-10-15T08:48:36.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74",
        "metadata": null,
        "log": {
            "start_time": 1728982117,
            "time_spent": 10,
            "attempts": 1,
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 5
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 8
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 10
                }
            ]
        },
        "fees": 6,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_95ujzol2na",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T08:48:46.000Z",
        "createdAt": "2024-10-15T08:48:36.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275662861,
        "domain": "test",
        "status": "abandoned",
        "reference": "v43w3ceb79",
        "amount": 1000,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T08:38:43.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74, 172.69.170.135, 172.31.68.120",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T08:38:43.000Z",
        "requested_amount": 1000,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275631304,
        "domain": "test",
        "status": "abandoned",
        "reference": "dg35j25ei7",
        "amount": 200,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T08:28:27.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T08:28:27.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275626853,
        "domain": "test",
        "status": "abandoned",
        "reference": "kfg3qm06bb",
        "amount": 200,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T08:26:54.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T08:26:54.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275609913,
        "domain": "test",
        "status": "abandoned",
        "reference": "fjj4jvecxj",
        "amount": 20,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T08:20:58.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78, 172.69.170.135, 172.31.62.52",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T08:20:58.000Z",
        "requested_amount": 20,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275566055,
        "domain": "test",
        "status": "success",
        "reference": "qgin0kqhp0",
        "amount": 4000,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T08:10:10.000Z",
        "created_at": "2024-10-15T08:09:53.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74",
        "metadata": null,
        "log": {
            "start_time": 1728979794,
            "time_spent": 17,
            "attempts": 1,
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 3
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 14
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 17
                }
            ]
        },
        "fees": 116,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_3a0rt1j7qq",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T08:10:10.000Z",
        "createdAt": "2024-10-15T08:09:53.000Z",
        "requested_amount": 4000,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275561227,
        "domain": "test",
        "status": "abandoned",
        "reference": "2z4ul3w9on",
        "amount": 9000,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T08:08:59.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74, 172.69.170.138, 172.31.62.52",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T08:08:59.000Z",
        "requested_amount": 9000,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275550010,
        "domain": "test",
        "status": "success",
        "reference": "qpto8ei2of",
        "amount": 3996,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T08:06:39.000Z",
        "created_at": "2024-10-15T08:06:25.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74",
        "metadata": null,
        "log": {
            "start_time": 1728979586,
            "time_spent": 14,
            "attempts": 1,
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 10
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 13
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 14
                }
            ]
        },
        "fees": 116,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_f6fyascvyp",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T08:06:39.000Z",
        "createdAt": "2024-10-15T08:06:25.000Z",
        "requested_amount": 3996,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275546229,
        "domain": "test",
        "status": "success",
        "reference": "s4so7yl3zl",
        "amount": 4,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T08:06:08.000Z",
        "created_at": "2024-10-15T08:05:30.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74",
        "metadata": null,
        "log": {
            "start_time": 1728979531,
            "time_spent": 37,
            "attempts": 2,
            "errors": 1,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 28
                },
                {
                    "type": "error",
                    "message": "Error: Declined",
                    "time": 29
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 36
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 37
                }
            ]
        },
        "fees": 1,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_7l86pdu0hr",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T08:06:08.000Z",
        "createdAt": "2024-10-15T08:05:30.000Z",
        "requested_amount": 4,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275541117,
        "domain": "test",
        "status": "success",
        "reference": "0rx2gjudb7",
        "amount": 200,
        "message": null,
        "gateway_response": "Approved",
        "paid_at": "2024-10-15T08:05:00.000Z",
        "created_at": "2024-10-15T08:04:16.000Z",
        "channel": "mobile_money",
        "currency": "KES",
        "ip_address": "102.135.172.74",
        "metadata": null,
        "log": {
            "start_time": 1728979458,
            "time_spent": 41,
            "attempts": 2,
            "errors": 0,
            "success": false,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: mpesa",
                    "time": 2
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with mobile money",
                    "time": 36
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with mobile money",
                    "time": 41
                }
            ]
        },
        "fees": 3,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_1urp7eyckz",
            "bin": "071XXX",
            "last4": "X000",
            "exp_month": "12",
            "exp_year": "9999",
            "channel": "mobile_money",
            "card_type": "",
            "bank": "M-PESA",
            "country_code": "KE",
            "brand": "M-pesa",
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T08:05:00.000Z",
        "createdAt": "2024-10-15T08:04:16.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275534221,
        "domain": "test",
        "status": "success",
        "reference": "98g0kyqnqc",
        "amount": 200,
        "message": null,
        "gateway_response": "Successful",
        "paid_at": "2024-10-15T08:02:55.000Z",
        "created_at": "2024-10-15T08:02:39.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74",
        "metadata": null,
        "log": {
            "start_time": 1728979362,
            "time_spent": 14,
            "attempts": 1,
            "errors": 0,
            "success": true,
            "mobile": true,
            "input": [],
            "history": [
                {
                    "type": "action",
                    "message": "Set payment method to: card",
                    "time": 4
                },
                {
                    "type": "action",
                    "message": "Attempted to pay with card",
                    "time": 12
                },
                {
                    "type": "success",
                    "message": "Successfully paid with card",
                    "time": 14
                }
            ]
        },
        "fees": 6,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": "AUTH_obztt4y6jc",
            "bin": "408408",
            "last4": "4081",
            "exp_month": "12",
            "exp_year": "2030",
            "channel": "card",
            "card_type": "visa ",
            "bank": "TEST BANK",
            "country_code": "KE",
            "brand": "visa",
            "reusable": true,
            "signature": "SIG_6iBLt8UucSVCN2rCS9HF",
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": "2024-10-15T08:02:55.000Z",
        "createdAt": "2024-10-15T08:02:39.000Z",
        "requested_amount": 200,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275497415,
        "domain": "test",
        "status": "abandoned",
        "reference": "z1i49rrv5i",
        "amount": 5,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T07:51:04.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.74, 172.69.170.135, 172.31.63.81",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T07:51:04.000Z",
        "requested_amount": 5,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275491672,
        "domain": "test",
        "status": "abandoned",
        "reference": "7byxn763ba",
        "amount": 90,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T07:49:11.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78, 172.69.170.140, 172.31.68.120",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T07:49:11.000Z",
        "requested_amount": 90,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    },
    {
        "id": 4275490116,
        "domain": "test",
        "status": "abandoned",
        "reference": "s0zl91vp0x",
        "amount": 90,
        "message": null,
        "gateway_response": "The transaction was not completed",
        "paid_at": null,
        "created_at": "2024-10-15T07:48:40.000Z",
        "channel": "card",
        "currency": "KES",
        "ip_address": "102.135.172.78, 172.69.170.140, 172.31.68.120",
        "metadata": null,
        "log": null,
        "fees": null,
        "fees_split": null,
        "customer": {
            "id": 197346057,
            "first_name": null,
            "last_name": null,
            "email": "daudited@gmail.com",
            "phone": null,
            "metadata": null,
            "customer_code": "CUS_qhtrhrqyapi1xa1",
            "risk_action": "default"
        },
        "authorization": {
            "authorization_code": null,
            "bin": null,
            "last4": null,
            "exp_month": null,
            "exp_year": null,
            "channel": null,
            "card_type": null,
            "bank": null,
            "country_code": null,
            "brand": null,
            "reusable": false,
            "signature": null,
            "account_name": null
        },
        "plan": {},
        "split": {},
        "subaccount": {},
        "order_id": null,
        "paidAt": null,
        "createdAt": "2024-10-15T07:48:40.000Z",
        "requested_amount": 90,
        "source": {
            "source": "merchant_api",
            "type": "api",
            "identifier": null,
            "entry_point": "transaction_initialize"
        },
        "connect": null,
        "pos_transaction_data": null
    }
]